### ISSUE TITLE
Requiered GeoNames Service

### ISSUE THREAD

**Issue by elektracodes** [isabelc/zodiacpress#7]
Would it be possible to change the GeoNames service in the future? Why did you choose this service instead of another one?

**Comment by isabelc** [comment]
GeoNames provides all the information required (latitude/longitude and timezone ID) in one request and it allows 30,000 daily requests for free. The Google Maps API would require 2 requests (one for latitude/longitude, and then another request for the timezone ID), and they only allow 2000 free requests per day. The cost would be too high to use Google Time Zone API. Also, purchasing extra credits costs less with GeoNames. I want to keep costs as low as possible for users of the plugin. 

Of course, I am open to other suggestions. I would possibly make an extension plugin that can change the GeoNames service to another one. I was going to make one to use Google web services, but its so expensive to use their services for a site that has even decent traffic, so I didn't do it.

**Comment by elektracodes** [comment]
Thank you for taking the time to answer it. 

My research also shows that GeoNames is the cheaper option. If I find something else I will inform you.
